name: Build on ARMv8

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest  # This will still use GitHub's runner, but you can modify it if using a self-hosted ARMv8 runner.

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build llama.cpp for ARMv8
        run: |
          # Create a build directory
          mkdir build
          cd build

          # Configure the build to target ARMv8 (you can adjust the flags based on your needs)
          cmake .. \
            -DCMAKE_SYSTEM_PROCESSOR=armv8-a \
            -DCMAKE_C_FLAGS="-mfpu=neon -march=armv8-a" \
            -DCMAKE_CXX_FLAGS="-mfpu=neon -march=armv8-a" \
            -DCMAKE_BUILD_TYPE=Release

          # Build the project
          make
